# Book settings
title: vOLT virtual Online Library Tutorials
author: Engineering & Physical Sciences Librarians
logo: EPS-Logo.png


execute:
  timeout: 500
  exclude_patterns:
    - 'crossref_library_module.ipynb'



html:
  home_page_in_navbar: false
  baseurl: https://eps-libraries-berkeley.github.io/volt
  use_repository_button     : true
  extra_footer: |
    <p>
    <a rel="license" 
     href="http://creativecommons.org/licenses/by-nc/4.0/">
     <img src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" style="border-width:0" alt="CCBYNC"/>
    </a>
    <br />
    This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>
    </p>
  google_analytics_id       : UA-3155703-1

sphinx:
  config:
    bibtex_reference_style: 'author_year' 
    html_show_copyright: false 
bibtex_bibfiles:
  - /references.bib   

latex:
  latex_documents:
    targetname: book.tex

launch_buttons:
  notebook_interface        : classic
  binderhub_url             : "https://mybinder.org"
  colab_url                 : "https://colab.research.google.com"

repository:
  url                       : https://github.com/EPS-Libraries-Berkeley/volt
  branch                    : main

