# Book settings
title: vOLT virtual Online Library Tutorials
author: Engineering & Physical Sciences Librarians
logo: EPS-Logo.png


execute:
  exclude_patterns:
    - 'crossref_library_module.ipynb'

html:
  home_page_in_navbar: false
  baseurl: https://eps-libraries-berkeley.github.io/volt

sphinx:
  extra_extensions: "sphinxcontrib.bibtex"

latex:
  latex_documents:
    targetname: book.tex

