# Book settings
title: vOLT virtual Online Library Tutorials
author: Engineering & Physical Sciences Librarians
logo: EPS-Logo.png

sphinx:
  extra_extensions: ""

latex:
  latex_documents:
    targetname: book.tex

execute:
  exclude_patterns:
    - 'crossref_library_module.ipynb'

html:
  home_page_in_navbar: false

